server:
  port: 80

spring:
  application:
    name: consumer-consul-feign-order

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        register: false

ribbon:
  ReadTimeOut: 5000
  ConnectTimeOut: 5000
