server:
  port: 83

spring:
  application:
    name: alibaba-nacos-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

service-url:
  nacos-payment-service: http://alibaba-nacos-provider
